### ISSUE TITLE
Support for NC24 and PHP8.1

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_u2f#1003]
On my NC24b3 instance running on Arch linux with PHP 8.1, upon `occ app:enable twofactor_u2f` and despite of adding `twofactor_u2f` to the `app_install_overwrite` array in `config/config.php` I cannot enable the app since this requirement cannot(?) be overruled:
```
cannot be installed because the following dependencies are not fulfilled:
PHP with a version lower than 8.0 is required.
```
This is due to [appinfo/info.xml](https://github.com/nextcloud/twofactor_u2f/blob/master/appinfo/info.xml) reading
```
<php min-version="7.3" max-version="8.0"/>
<nextcloud min-version="20" max-version="23"/>
```
Please change [appinfo/info.xml](https://github.com/nextcloud/twofactor_u2f/blob/master/appinfo/info.xml) to
```
<php min-version="7.3" max-version="8.1"/>
<nextcloud min-version="21" max-version="24"/>
```
according to the most recent [app upgrade guide](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_24.html).

I'm not doing a PR since I cannot check or tell whether anything else must be changed (although I don't expect it).

Manually changing [appinfo/info.xml](https://github.com/nextcloud/twofactor_u2f/blob/master/appinfo/info.xml) and enabling the app works fine for me with NC24 and PHP8.1.

**Comment by ChristophWurst** [comment]
Considering https://github.com/nextcloud/twofactor_u2f/issues/947 I don't know if we even do another release. I'll have a  look.

**Comment by Showfom** [comment]
Please support NC 24, we are waiting for update.

Thanks for your great app.

**Comment by nursoda** [comment]
I [switched](https://github.com/nextcloud/twofactor_u2f/issues/947#issuecomment-1113586971) to [twofactor_webauthn](https://github.com/nextcloud/twofactor_webauthn), works for me.

@ChristophWurst you should decide and tell people whether to expect a release for NC24 or not.

**Comment by gituser789** [comment]
Same issue here. 
Can we update, or should we switch to twofactor_webauthn?

![nextcloud](https://user-images.githubusercontent.com/62549000/170193593-b503a172-a681-4474-b19a-1b67394d7046.png)

**Comment by ChristophWurst** [comment]
You should switch

**Comment by ChristophWurst** [comment]
We are phasing out this app. There will be no more features or support for newer Nextcloud/PHP.

**Comment by gituser789** [comment]
ok, thanks!
