### ISSUE TITLE
Webauthn in Nextcloud does only provide 1FA, not 2FA, thus it should not be recommended as a successor to this app

### ISSUE THREAD

**Issue by RoWo-DS** [nextcloud/twofactor_u2f#1022]
In your documentation, you write "The [Two-Factor WebAuthn](https://apps.nextcloud.com/apps/twofactor_webauthn) app can be used as a replacement." to suggest people to migrate from U2F to Webauthn to continue 2FA on Nextcloud.

Webauthn on Nextcloud does not provide 2FA. It only provides 1FA. See https://hwsecurity.dev/2020/08/webauthn-pin-bypass/ for more details.

Please correct your documentation. TOTP could be mentioned as an alternative to U2F for Nextcloud.

**Comment by ChristophWurst** [comment]
There are two things we do with webauthn
1) Passwordless login - uses webauthn without a pin and can be used in combination with totp etc. For pin support see https://github.com/nextcloud/server/issues/21215
2) Second factor challenge - this app. WebAuthn is used *after* you enter your password. It doesn't replace your password. So it is second login factor to your password.

Does that make sense?

**Comment by RoWo-DS** [comment]
Great, thanks for your answer. Actually I didn't understand, that by default WebAuthn is already available for 1FA and with this app here WebAuthn is in addition also available for 2FA.

Thank you very much!
