### ISSUE TITLE
PHP with a version lower than 8.0 is required.

### ISSUE THREAD

**Issue by dapor2000** [nextcloud/twofactor_u2f#1032]
### Steps to reproduce
1. Update NC to Version [Nextcloud Hub 5](https://nextcloud.com/) (27.0.1)
2. try login with U2F
3. no login possible

### Expected behaviour
login success

### Actual behaviour
again a U2F token is requested

### Server configuration

**Operating system**:  Docker

**Web server:** Apache

**Database:** Mysql

**PHP version:** ?

**Version:** (see admin page) [Nextcloud Hub 5] (27.0.1)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_u2f#%EF%B8%8F-deprecated-%EF%B8%8F-u2f-second-factor-provider-for-nextcloud

**Comment by dapor2000** [comment]
Great, but useless:

docker exec  nextcloud  php occ twofactor_webauthn:migrate-u2f --all

  There are no commands defined in the "twofactor_webauthn" namespace.
