### ISSUE TITLE
A2F over NFC on Android does't work anymore

### ISSUE THREAD

**Issue by paul4haren** [nextcloud/twofactor_u2f#144]
I am Using several instances of Nextcloud (13.01) 
FIDO A2F works fine on my Linux Desktop, even with Firefox (59.0.1) 
But I can't use my tokens on my Android-Devices anymore. (Android 7; Chrome).
Also not with Bluethooth anymore,
NB
1) Some time ago ( a month or so) both methods (NFC and Bluetooth worked fine.
2. On the demo-pages from Yubiko and Google both methods work fine.

**Comment by ChristophWurst** [comment]
Try [v1.5.2](https://github.com/nextcloud/twofactor_u2f/releases/tag/1.5.2) -- there was an unfortunate breakage in the u2f lib and this release should have fixed that.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_u2f/pull/154
