### ISSUE TITLE
register multiple U2Fs

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_u2f#15]
According to [Yubico](https://developers.yubico.com/U2F/) it is recommended to have multiple U2Fs for every Service. Sadly NC can only register one.

>Users are recommended to register at least two U2F devices with every service provider, which may optionally also provide the user with a backup code should a U2F device be misplaced.

**Comment by ChristophWurst** [comment]
Hi,
of course it makes sense to extend this app in that regards. In fact, the server-side implementation already allows you to have multiple registered devices: https://github.com/nextcloud/twofactor_u2f/blob/master/lib/Service/U2FManager.php. What's still missing is a UI that is capable of adding more than one device. That should be easy 😉

**Comment by My1** [comment]
nice2know

**Comment by borghal** [comment]
I'd like to see this implemented, too. 

I'm already very impressed by how easy it is to use a yubikey in NC11. Keep up the good work!

**Comment by ChristophWurst** [comment]
> I'm already very impressed by how easy it is to use a yubikey in NC11. Keep up the good work!

Thank you very much! Would be cool if you could rate the app on https://apps.nextcloud.com/apps/twofactor_u2f too :-)

**Comment by borghal** [comment]
Done :-)

**Comment by fti7** [comment]
+1 for Multiple U2F-Devices

**Comment by Makki1** [comment]
+1 from me, works so far

**Comment by ChristophWurst** [comment]
(deleted +1 comments. use github reactions instead please)
