### ISSUE TITLE
Version on apps.nextcloud.com not updated

### ISSUE THREAD

**Issue by Sp1l** [nextcloud/twofactor_u2f#164]
Not sure if this should be an issue here.

On apps.nextcloud.com the version is still 1.5.1 which is incompatible with latest Nextcloud 13 release.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/appstore/issues/560.

What version of Nextcloud are you using? 13.0.2 should get 1.5.4, even though it's not listed on the app store website.

**Comment by ChristophWurst** [comment]
![bildschirmfoto von 2018-05-07 11-57-30](https://user-images.githubusercontent.com/1374172/39696376-db8c3fde-51ed-11e8-8279-6c99768d1d4a.png)

**Comment by borghal** [comment]
For what it's worth, I only see version 1.5.1 in the apps menu using nextcloud 13.0.2, too. App store website also shows 1.5.1.
I'd love to upgrade, do I have to do so manually?

**Comment by ChristophWurst** [comment]
> 13.0.2 should get 1.5.4, even though it's not listed on the app store website.

My bad, https://github.com/nextcloud/server/pull/9024 was actually not backported to `stable13`. I'll publish a new release today that will allow all versions of Nextcloud 13.

Sorry for the inconveniences.

**Comment by Sp1l** [comment]
Thanks Christoph 😄 and it was only that, a small inconvenience. Love the U2F app for Nextcloud!

**Comment by ChristophWurst** [comment]
Thanks :heart: 

I'm closing this as resolved.
