### ISSUE TITLE
No error message for failed u2f sign request

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_u2f#167]
### Steps to reproduce
1. Try to sign in, but with a key that has not been registered

### Expected behaviour
See a nice error message that signing the challenge failed.

### Actual behaviour
Nothing.

**Comment by MikeZuluUSA** [comment]
Same issue over here. Nextcloud 13.0.6. u2f version 1.55. chrome 68.0.3440.106
Yubikey not able to register through app. Always say u2f not supported. 
10/10 failure quote 100%

How can I see the errors in the dev console of chrome (F12 key)...
JQMIGRATE: Migrate is installed, version 1.4.0
security:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden">​…​</form>​
DevTools failed to parse SourceMap: https://xxxxxxxx/core/vendor/purify.min.js.map
onloadwff.js:58 [Violation] 'setTimeout' handler took 95ms

**Comment by ChristophWurst** [comment]
This was fixed in #286
