### ISSUE TITLE
U2F for Safari works - Please test and Enable

### ISSUE THREAD

**Issue by stgarf** [nextcloud/twofactor_u2f#168]
### Feature Request

U2F for Safari works - Please test and Enable

#### Summary

I've tested it by 
1. downloading and compiling [Safari-FIDO-U2F](../../../Safari-FIDO-U2F/Safari-FIDO-U2F) then setting my user agent to Chrome (because the script is checking ;) ):
    <img width="963" alt="screen shot 2018-05-16 at 11 44 20 pm" src="https://user-images.githubusercontent.com/1694002/40160846-bee0fc1c-5963-11e8-8b44-eaa760f52095.png">

1. Registering my OnlyKey:
    <img width="517" alt="screen shot 2018-05-16 at 11 53 41 pm" src="https://user-images.githubusercontent.com/1694002/40161053-6388e9f0-5964-11e8-9d56-7e09fb20544d.png">

1. Then logging out and in:
    <img width="1920" alt="screen shot 2018-05-16 at 11 44 38 pm" src="https://user-images.githubusercontent.com/1694002/40160963-28e441b4-5964-11e8-9d27-47f6d12c494f.png">

1. Profit!
    🚢

**Comment by ChristophWurst** [comment]
Hey!

Would you mind updating https://github.com/nextcloud/twofactor_u2f#requirements? Just file a pull request and I'll happily review and merge this.



> setting my user agent to Chrome (because the script is checking ;) ):

Which script?

Thanks for your feedback!

**Comment by stgarf** [comment]
> Which script?

I'm not 100% sure but it's maybe [this logic](https://github.com/nextcloud/twofactor_u2f/blob/master/js/settingsview.js#L263) that returns the error message `"Chrome is the only browser that supports U2F devices. You need to install the "U2F Support Add-on" on Firefox to use U2F."` that prevents both registration and login with u2f unless you spoof the user-agent.

**Comment by ChristophWurst** [comment]
> I'm not 100% sure but it's maybe this logic that returns the error message "Chrome is the only browser that supports U2F devices. You need to install the "U2F Support Add-on" on Firefox to use U2F." that prevents both registration and login with u2f unless you spoof the user-agent.

No, that message is shown regardless of the browser in use.

**Comment by ChristophWurst** [comment]
As of https://github.com/nextcloud/twofactor_u2f/commit/0bb0a8e61b1d835e5d9f8f2553c01441fd989d1a, we let the u2f lib determine whether u2f is supported by the current browser: https://github.com/nextcloud/twofactor_u2f/commit/0bb0a8e61b1d835e5d9f8f2553c01441fd989d1a#diff-d62d2e0c077ab3cbd1190255d987bed3R60

Thanks :v:
