### ISSUE TITLE
FIDO2

### ISSUE THREAD

**Issue by tatramaco** [nextcloud/twofactor_u2f#185]
### Feature Request

Switch to the new new FIDO2/W3 APIs that are U2F backwards compatible ?

**Comment by ChristophWurst** [comment]
Hi,

I've looked into this last week but I couldn't find any good resources on how to use this new standard. Do you happen to have more experience with this? Can we use the browser APIs directly or should we use an abstraction (similar to the u2f lib we're using right now)?

Thanks for filing a feature request for this :)

**Comment by tatramaco** [comment]
Hi, I am just starting out looking into this also.

My understanding is that we can use the new W3 APIs in the browser

**Comment by ChristophWurst** [comment]
Okay cool. Let me know when you know more about that and we can see how to integrate this here :)

**Comment by ChristophWurst** [comment]
I think we can close this in favor of #342
