### ISSUE TITLE
Cannot enable the app on Nextcloud 14

### ISSUE THREAD

**Issue by z3ntu** [nextcloud/twofactor_u2f#232]
I have version 1.6.1 installed on my server but cannot enable it due to 

> This app cannot be installed because the following dependencies are not fulfilled:
>
> * Server version 13 or lower is required.

**Comment by ChristophWurst** [comment]
How did you install the app?

The app *is* compatible: https://github.com/nextcloud/twofactor_u2f/blob/09a82ddbf846e9fe5bcb2b7382d6ed35695fada7/appinfo/info.xml#L21

**Comment by z3ntu** [comment]
I had it installed before the upgrade, during the upgrade it said that the app would be disabled, then I upgraded to 1.6.1 and see this message.

Upgrade log: https://pastebin.com/raw/UJaRjzRK

Screenshot: 
![image](https://user-images.githubusercontent.com/3768500/45203115-5b764800-b27b-11e8-97fb-03f394d03b05.png)

**Comment by z3ntu** [comment]
But actually your CI says the same thing: https://travis-ci.org/nextcloud/twofactor_u2f/jobs/425290407#L1876

**Comment by ChristophWurst** [comment]
> But actually your CI says the same thing

Yes, because it sets up master, which is Nextcloud 15 :wink:

**Comment by z3ntu** [comment]
Interesting. After reloading the apps page I can enable it... Sorry...

**Comment by ChristophWurst** [comment]
No worries. This might still be a bug in the server. So if you can reproduce this somehow or it happens again, please report this [here](https://github.com/nextcloud/server/issues/new)!

**Comment by z3ntu** [comment]
I'd guess (from what I have done) that when the version compatibility information changes during an app upgrade, it doesn't refresh if it's actually compatible with the new version. But the behavior was just the one time, but yes, it seems like a bug and no, I can't reproduce it without probably downgrading and upgrading the versions.

**Comment by z3ntu** [comment]
I saw basically the same thing again with the NC15 upgrade (app was disabled at upgrade time and showed as requiring NC14 on the details page until I reloaded the page - now it's php 7.3 that it doesn't like :wink: )

**Comment by vtolkanov** [comment]
Hi ~
I have a app that I used on NC14. Now I upgraded server to NC15, but can't enable that app ~
Will you kindly let me know the reason of such things?
