### ISSUE TITLE
Shorten `twofactor_u2f_registrations` index name

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_u2f#258]
```
 php ../../occ app:check-code twofactor_u2f
Database schema error: Name of table *dbprefix*twofactor_u2f_registrations is too long (27), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
App is not compliant
```

cc @rullzer

**Comment by rullzer** [comment]
Ah pfff I hate that... but yeah probably just copying the data over to a new table should work just fine... I can try to look into it.

**Comment by ChristophWurst** [comment]
Should we look into table rename migrations at some point?

**Comment by ChristophWurst** [comment]
Just checked and the `AbstractSchemaManager` we use for our `IDBConnection` abstraction supports `::renameTable($name, $newName)`. We'd just have to export that and keep track of renamed tables. cc @nickvergessen

**Comment by nickvergessen** [comment]
> Should we look into table rename migrations at some point?

The thing is with autoincrements it's always dangerous to try automation. I'm still not sure all dbs support inserting autoincrement without problems.

**Comment by ChristophWurst** [comment]
But that actually means renaming the table is the safer operation then because there you don't have any inserts.

**Comment by ciroiriarte** [comment]
Seeing a similar error after upgrading to NC15:

```
wwwrun@nas02:/srv/www/htdocs/nextcloud> ./occ app:check-code twofactor_u2f
The current PHP memory limit is below the recommended value of 512MB.
Analysing /srv/www/htdocs/nextcloud/apps/twofactor_u2f/lib/Migration/Version010601Date20181022142736.php
 1 errors
    line   47: twofactor_u2f_registrations - Table name is too long because of autoincrement (max. 21)
App is not compliant

```

**Comment by ChristophWurst** [comment]
> Seeing a similar error after upgrading to NC15:

FYI this is not an error.

**Comment by ciroiriarte** [comment]
Seems so. Enabled the app anyway and it's working..

**Comment by ChristophWurst** [comment]
```
> php occ app:check-code twofactor_u2f
> App is compliant - awesome job!
```

well :man_shrugging:
