### ISSUE TITLE
Chat plugin available on the U2F verification screen

### ISSUE THREAD

**Issue by itay-grudev** [nextcloud/twofactor_u2f#27]
I am using the JavaScript XMPP Chat plugin and on the U2F verification page the chat windows are available, which is a security issue.

I am unsure whether this is an issue from your plugin or the JavaScript XMPP Chat. Please advise.

**Comment by ChristophWurst** [comment]
> I am unsure whether this is an issue from your plugin or the JavaScript XMPP Chat. Please advise.

This is clearly an issue of the chat app. Even if displayed there, it should not function since request are not considered valid before the 2FA challenge has been solved. Please file an issue in the chat app's repo. Thanks :)
