### ISSUE TITLE
u2f blocks ocs api and MacOS desktop client

### ISSUE THREAD

**Issue by Pectojin** [nextcloud/twofactor_u2f#32]
When I enable u2f my MacOS desktop client fails to login. Even setting up the client from scratch fails with user unauthorized. 

Additionally, I have a script using the ocs API, which gets the following error after U2F is enabled:
      < status >failure</ status >
      < statuscode >997</ statuscode >
      < message >Current user is not logged in</ message >

Is there any way to disable u2f on ocs API and for the desktop client? I get that it's less secure, but even if I could, I wouldn't want to use my u2f every time my script runs. And for desktop client u2f obviously has to be disabled until the client supports it.

**Comment by LukasReschke** [comment]
Create an application specific password in your personal settings.

**Comment by Pectojin** [comment]
Appreciate the quick response.

This works as expected, thanks!
