### ISSUE TITLE
calendar & contacts can't be synced any more

### ISSUE THREAD

**Issue by unDocUMeantIt** [nextcloud/twofactor_u2f#33]
hi,

first of all, this is great work, thank you! i just installed the app and registered a yubikey neo, works like a charm and is very intuitive.

however, as soon as i activated the U2F device, my smartphone complained that it can no longer sync calendars and contacts (i'm using DAVdroid on an android phone, it says username/password don't match any more). i don't know if this is to be expected, as the overall description of the app's functionality is maybe a bit sparse ;-)

i was assuming that U2F was mainly protecting the login to the web frontend, but you could still use those services. it would be a bit impractical to authenticate your devices each time the calendars would like to sync, as this could be every five minutes or so. is there something i can do about this?

**Comment by ChristophWurst** [comment]
Hey,

use app-specific passwords on your devices. You can generate those in your personal settings :wink:

**Comment by unDocUMeantIt** [comment]
ah, great! i didn't see that connection. now that i know what to look for i also found some documentation. 

this shouldn't happen. it would improve the user experience if you added an immediate warning message when a user activates U2F, to specifically point this out. especially if app specific passwords are not being used yet.

thanks!

**Comment by ChristophWurst** [comment]
Yup, good point. This is definitelly be added to the user interface!
