### ISSUE TITLE
u2f combined with desktop app

### ISSUE THREAD

**Issue by javl** [nextcloud/twofactor_u2f#333]
I'm not sure if this is a bug I need to mention here, in the u2f repo, or in the nextcloud desktop client repo. The problem lies with settings not being accessible in the desktop client, but the goal of changing the settings is to use the u2f app.
 
### Steps to reproduce
1. Enable u2f devices in Firefox by setting ```security.webauth.u2f``` via ```about:config```
2. Install and setup u2f app via nextcloud webclient
3. Start nextcloud locally using ```../Nextcloud-2.5.1-x86_64.AppImage```
4. Firefox version in appimage doesn't recognize hardware device

When the desktop client starts, it shows: "Please log in before granting Mozilla/5.0 (Linux) mirall/2.5.1final (build 20181204) access to your Nextcloud." which leads me to believe it is using its own version of Firefox, where the ```security.webauth.u2f``` has not been set. The log confirms this setting missing: ```Error: U2F not supported```

Problem is, there is no (obvious) way to access the ```about:config``` of the Firefox version being used by the appimage.

**Used nextcloud appimage**
Nextcloud-2.5.1-x86_64.AppImage

**Installed Firefox version**
Firefox 64

**Operating system**:
Up to date Debian "Stretch" Linux
Nextcloud-2.5.1-x86_64.AppImage

**Comment by ChristophWurst** [comment]
An alternative approach would be to generate an app password on the Firefox instance where you've configured the app and use that to log in. Would that work for you?

**Comment by ChristophWurst** [comment]
cc @rullzer

**Comment by javl** [comment]
@ChristophWurst I was just trying that, and can confirm it works. It does defeat the purpose of the 2f app, at least in the local sync client. But it's better than having to turn 2f off completely (as now it still works in the webclient). 

I would like to be able to just enable the hardware token inside the desktop client though. I tried starting the appimage with the ```--confdir``` argument pointing to different directories inside ```~/.mozilla/firefox```, hoping I could just have it use the settings from my regular Firefox, but no luck. (Though I didn't test this thoroughly and this is more related to the desktop client than u2f app anyway).

Thanks

**Comment by rullzer** [comment]
Actually it is not opening firefox but rather a webview. I do not think hardware tokens are supported there yet indeed...

**Comment by ChristophWurst** [comment]
> @ChristophWurst I was just trying that, and can confirm it works. It does defeat the purpose of the 2f app, at least in the local sync client. But it's better than having to turn 2f off completely (as now it still works in the webclient).

You only have to do this once to set the client up. Alternatively you could install & configure a second 2FA provider like TOTP which is usable in this web view and other clients without u2f (e.g. your phone).

**Comment by ChristophWurst** [comment]
Closing as u2f is simply not supported by the browser engine of the web view.

Thanks for reporting :v:
