### ISSUE TITLE
U2F device registration failed (error code 2)

### ISSUE THREAD

**Issue by hellix08** [nextcloud/twofactor_u2f#35]
I downloaded the app from GitHub, updated and enabled it but when I go in personal settings and check

Use U2F device

It fails and the error: _"U2F device registration failed (error code 2)"_ pops up

Using:
NextCloud 11.0.1 (stable)
Two Factor U2F 1.1.0

**Comment by ChristophWurst** [comment]
Ref https://developers.yubico.com/U2F/Libraries/Client_error_codes.html

**Comment by hellix08** [comment]
Solved by putting https:// before the url, so

192.168.x.x/nextcloud/blablabla
becomes
https://192.168.x.x/nextcloud/blablabla

**Comment by Tealk144** [comment]
Hi, i have the same Issue but i dont know why.

**Comment by ChristophWurst** [comment]
Please file a new issue. Thanks! :)
