### ISSUE TITLE
Key without name causes rendering errors

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_u2f#352]
### Steps to reproduce
1. Have a key registered without a name (don't know if this is reproducible with the latest versions)
2. Open the settings page

### Expected behaviour
See the list of registered devices

### Actual behaviour
An error at https://github.com/nextcloud/twofactor_u2f/blob/2ccba83c099ca21f04ee3b3fd76f798bfb9828a4/src/main-settings.js#L32

cc @rullzer

**Comment by rullzer** [comment]
I'll keep my instance in the current state for now. So I can test once a fix is there.
