### ISSUE TITLE
U2F broken after upgrade from Nextcloud 14 to 15

### ISSUE THREAD

**Issue by jinnko** [nextcloud/twofactor_u2f#392]
### Steps to reproduce

1. Upgraded from latest Nextcloud 14 official docker image to Nextcloud 15
2. Followed the upgrade steps of running `./occ upgrade`
3. Had to disable U2F and remove all keys via `occ` to get in, then upgraded all the apps to be Nextcloud 15 compatible
4. Now am unable to re-enable U2F access

### Expected behaviour

Under [Settings > Security] I expect the [Add U2F device] button to trigger the browser (latest Firefox on Ubuntu, 65.0.1), to pop up the U2F touch prompt.

### Actual behaviour

When clicking on the [Add U2F device] button nothing happens and the in page spinner displays with the message "Please plug in your U2F device and press the device button to authorize. "

### Server configuration

**Operating system**:

Official Nextcloud 15.0.5.3 docker container.

**Web server:**

Apache2, from within the container

**Database:**

MariaDB 10.1.37-MariaDB-0+deb9u1

**PHP version:**

```
# docker exec -it nextcloud php --version
PHP 7.2.16 (cli) (built: Mar  9 2019 01:49:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16, Copyright (c) 1999-2018, by Zend Technologies
```

**Version:** (see admin page)

Nextcloud 15.0.5.3: `nextcloud:stable` from https://hub.docker.com/_/nextcloud/

**Updated from an older version or fresh install:**

Upgraded from Nextcloud 14 a few weeks ago, worked before upgrade, broken after upgrade.

**List of activated apps:**

```
# docker exec -it -u www-data nextcloud php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - camerarawpreviews: 0.6.3
  - carnet: 0.13.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - deck: 0.5.2
  - drawio: 0.9.2
  - event_update_notification: 0.3.3
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - news: 13.1.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.1
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.0.3
  - twofactor_totp: 2.1.2
  - twofactor_u2f: 2.1.2
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```

**The content of config/config.php:**
```
# docker exec -it -u www-data nextcloud php occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/***REMOVED_VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "auth.bruteforce.protection.enabled": false,
        "mysql.utf8mb4": true
    }
}
```

#### Client configuration
**Browser:**

Firefox 65.0.1, Ubuntu 18.04 stock

**Operating system:**

Ubuntu 18.04

##### Web server error log

```
[Mon Mar 11 12:20:59.538350 2019] [authz_core:error] [pid 4055] [client 127.0.0.1:49146] AH01630: client denied by server configuration: /var/www/html/data/.ocdata
...
Mar 11 12:21:50 ht-xm-2 nextcloud[6866]: 127.0.0.1 - - [11/Mar/2019:12:21:50 +0000] "POST /index.php/apps/twofactor_u2f/settings/startregister HTTP/1.1" 200 938 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
```

##### Server log (data/nextcloud.log)

- Nothing appears during the steps to reproduce the issue

##### Browser log

When loading `/index.php/settings/user/security`, the following errors are emitted:

```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). 2 security:1:1
XML Parsing Error: not well-formed
Location: https://nextcloud/core/fonts/Nunito-Regular.woff2
Line Number 1, Column 5: Nunito-Regular.woff2:1:5
```

After pressing the [Add U2F device] button the following is emitted:

```
starting u2f registration AddDeviceDialog.vue:109
Error: "Registration failed"
	u u2f-api.js:71
	register u2f-api.js:114
	register u2f-api.js:121
	S ncvuecomponents.js:128
	register u2f-api.js:111
	N ncvuecomponents.js:128
	N ncvuecomponents.js:128
	u ncvuecomponents.js:128
 ncvuecomponents.js:128:44943
```

**Comment by ChristophWurst** [comment]
Closing as the issue template does not contain any information regarding your issue.

I assume you have a misconfigured setup. Please see the documentation.

**Comment by jinnko** [comment]
@ChristophWurst - you were too quick for me.  I accidentally hit enter after setting the title, then spent the next 30-40m gathering all the info for the ticket.  Could you re-open this or should I raise a new one with the same info?

**Comment by ChristophWurst** [comment]
Sorry

**Comment by ChristophWurst** [comment]
Are you running a proxy? Did you change your domain? https://github.com/nextcloud/twofactor_u2f/issues/325

**Comment by ChristophWurst** [comment]
> Location: https://nextcloud.ixydo.org/core/fonts/Nunito-Regular.woff2

You have to fix your webserver config to serve `woff` *and* `woff2`

**Comment by jinnko** [comment]
When I curl that URL the server returns an HTTP 200 and the 98K content of the woff2 file.  Could it be the failures in the CSP headers causing the problem?

nginx is proxying the requests to the container, but there's been no other indications of problems, and the config hasn't changed during the Nextcloud 14 to 15 change.

**Comment by ChristophWurst** [comment]
Okay, just see https://github.com/nextcloud/twofactor_u2f/issues/325#issuecomment-458698728 in case you haven't set that config for your server. It will make the old registrations work again. I can't really tell what has changed in 15 to cause this but apparently some users ran into issue running Nextcloud behind a reverse proxy.

> When I curl that URL the server returns an HTTP 200 and the 98K content of the woff2 file. Could it be the failures in the CSP headers causing the problem?

Maybe it's best to see https://help.nextcloud.com/ for that. I can't tell if that is caused by the CSP or some other config.

**Comment by jinnko** [comment]
Thanks @ChristophWurst for linking to that specific comment - that has resolved the issue.

Earlier I said nginx is proxying, but in fact it's haproxy.  The proxy is injecting:

- one request header: `X-Forwarded-Proto: https`
- one response header `Strict-Transport-Security: max-age=15552000; includeSubDomains`
