### ISSUE TITLE
"U2F device" not displayed in selected language.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/twofactor_u2f#411]
## Expected behavior
All kind of text strings should be displayed in the selected language.

## Current behavior
The "**U2F device**" category header under **Settings>Personal>Security** is not translated into German language ("**U2F-Gerät**") although a correct translation exists.

![20190402_nc_settings_u2f_translation_of_-U2F_device-](https://user-images.githubusercontent.com/2572764/55399074-6a3f8780-554a-11e9-9b76-4dab786b5477.png)

## Steps to reproduce
1. open the settings dialog
2. navigate to Personal > Security

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5
Two-Factor U2F app version: 2.1.2

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by ChristophWurst** [comment]
Thank you! Fix is at https://github.com/nextcloud/twofactor_u2f/pull/412. I'm surprised nobody has noticed this before.
