### ISSUE TITLE
Allow keys to be used on multiple domains

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/twofactor_u2f#418]
I sometimes switch to using my local domain for faster transfer and to avoid hitting my ISP's data cap when I'm at home. I know of #28 but I'm not 100% sure why U2F is bound to domain name instead of a user account. 

I feel an option should be added to allow keys to be used on multiple domains.

**Comment by ChristophWurst** [comment]
> U2F is bound to domain name

It's bound to the domain.

You can also simple configure your local dns to serve the local Nextcloud instance from the same domain as it is served externally. This should work just fine and fix this problem.
