### ISSUE TITLE
1.3.1 seems to have broken Chrome authentication

### ISSUE THREAD

**Issue by docfuz** [nextcloud/twofactor_u2f#45]
I just installed 1.3.1 on NC11. I was previously using 1.2.0.
Now I can log in with TOTP, but not with U2F. I deleted my previous token and enrolled a new one.
I'm using a Yubikey Neo, Chrome 58.0.3029.96 (64-bit) on latest Mac OS 10.12.4.

It works under Firefox with the U2F extension, but not with Chrome, now. It seems to be stuck and doesn't send anything to the server. Moreover, I used my token to login to Github to open this issue. Although I don't usually reboot to swipe errors under the carpet, I tried to close and open a new Chrome instance. Obviously it didn't change anything :-)

BTW, thank you for your work, the two authentication apps for NC really rock.
doc

EDIT: I can confirm that reverting back to 1.2.0 makes my Chrome working again.

**Comment by docfuz** [comment]
I tried 1.3.0 and it **works**. Tried again 1.3.1 to be sure it is not me, and it **doesn't**.

One more thing: in both 1.3.0 and 1.3.1 I don't seem to be able to register more than one device, though I tried registering the same yubikey more than once. I get error 4.

**Comment by Nibbels** [comment]
I am not sure, if I am testing the right thing here, but:

**Chrome Windows 10 x64 Version 58.0.3029.96 (64-bit)**
I tested 1.3.0 and 1.3.1 and I am successfully able to register two plug-up U2F keys.
When I register some key twice `Error 4` gets displayed as it should be.

[In case this bug is hard to find and not an obvious thing: I had Chrome 59 beta installed last week and my chat did not work anymore. This is some pushchat that adds JSON step by step/line by line to some continious downloadstream.
This works perfectly until Chrome 58, but not in Chrome 59 beta.
The error was some parsing error for JSON and states to have some not allowed invisible chars somewhere. -> In case multiple sticks are added with multiple json_encode($thing) check for this! The F12`s console should show this.]

**Comment by go2sh** [comment]
I can confirm the issue.
```
Unknown or missing requestId in response.
u2f.responseHandler_ @ u2f-api.js?v=3b626d6…:608
(anonymous) @ u2f-api.js?v=3b626d6…:384
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnMessage @ extensions::messaging:320
```
Devtools log.

**Comment by Nibbels** [comment]
Yes, Login is a problem!

![screenshot_6](https://cloud.githubusercontent.com/assets/3265671/25742292/171ee874-318f-11e7-85c3-c234949452f7.png)

Within Firefox it works on both Sticks.

When I change this file:
![screenshot_7](https://cloud.githubusercontent.com/assets/3265671/25742413/a957d8cc-318f-11e7-9a88-accfa2563f03.png)
Therefore the 1.3.0 should work as expected?

**Comment by ChristophWurst** [comment]
> Therefore the 1.3.0 should work as expected?

No. In 1.3.0 there was a problem with using multiple U2F devices. You can register them, but only the very first one can be used to log in.

**Comment by Nibbels** [comment]
With the change to 1.3.0 state atop:

Firefox: Two sticks can login.
Chrome Windows 10 x64 Version 58.0.3029.96 (64-bit): **Two sticks can login!!**

**Comment by go2sh** [comment]
6e20eb5615c20c6059fd01a18e13d73282297541 broke it. Now the u2f api gets called with wrong parameters.  See https://github.com/nextcloud/twofactor_u2f/blob/master/js/vendor/u2f-api.js#L627 and
https://github.com/nextcloud/twofactor_u2f/blob/master/js/challenge.js#L40.

**Comment by ChristophWurst** [comment]
Could you please open a PR with the fix? I'll try to test it ASAP. cc @LukasReschke

**Comment by go2sh** [comment]
@ChristophWurst I just did a quick review of the code in general. Apparently, U2F API has changed and the app needs some adaption. E.g. transports have been added, which are currently not supported by the app. So all in all, I can do a quick fix but there is some work to do to support it properly from my point of view. I'll open a new issue with every thing i found.

**Comment by go2sh** [comment]
@ChristophWurst for a super super quick fix revert 6e20eb5615c20c6059fd01a18e13d73282297541. But as I mentioned, #47 the root cause lies somewhere else. I'am currently at work and have no time nor the setup to test and fix it. I just stumbled on this issue as I updated today and locked myself out.^^

**Comment by ChristophWurst** [comment]
My testing results: reverted 6e20eb5 as suggested, which brings me back to the state of 1.3.0. I could register both my keys on FF and log in with either of them on Chrome. However, I still could only log in with one of the keys when using FF. This is totally strange. I really wonder why https://github.com/nextcloud/twofactor_u2f/issues/45#issuecomment-299434704 should have worked.

**Comment by ChristophWurst** [comment]
I'm still wondering whether it's correct to pass only the *first* challenge to `u2f.sign` like https://github.com/nextcloud/twofactor_u2f/blob/d05626c3f76441a31c46cb82fd0249913b653ae1/js/challenge.js#L44 …

**Comment by ChristophWurst** [comment]
Btw, when the login signing request fails, [this](https://github.com/Yubico/php-u2flib-server/blob/25863d132500f7da0d6e89ca0d1805b6c81c6267/src/u2flib_server/U2F.php#L296) exception is thrown.

**Comment by Nibbels** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/3265671/25761773/49654e7a-31dc-11e7-86f3-3a377ea8a3e6.png)
I retested Firefox twice, it worked. Both keys worked while logging in. With two keys registered.

Then I updated Firefox and retested.
![screenshot_5](https://cloud.githubusercontent.com/assets/3265671/25761851/91e612b0-31dc-11e7-9e41-604ef03eac79.png)
Still working! Both keys can log in.

When I deactivate 
![screenshot_6](https://cloud.githubusercontent.com/assets/3265671/25761901/c63e1a1c-31dc-11e7-8253-83310a3faf3c.png)
No Key works. So I guess that there is no "new native U2F function" interfering here.

Enabling the Expansion again makes both of my keys work again.

**Comment by ChristophWurst** [comment]
I have updated the u2f lib in https://github.com/nextcloud/twofactor_u2f/pull/49. Let's continue there 😉 

Not that you created the PR from a branch of your personal fork. This means I cannot push to it. You do have permissions to push a branch directly to this repo though, as you're one of the collaborators!

**Comment by ChristophWurst** [comment]
> I have updated the u2f lib in #49. Let's continue there 😉
> 
> Not that you created the PR from a branch of your personal fork. This means I cannot push to it. You do have permissions to push a branch directly to this repo though, as you're one of the collaborators!

nvm, wrong ticket
