### ISSUE TITLE
Error with oc_twofactor_backup_codes

### ISSUE THREAD

**Issue by Nibbels** [nextcloud/twofactor_u2f#46]
I had everything tested with 1.3.0 and it worked. Some week ago I upgraded Nextcloud to Nextcloud 11.0.3 (stable)

When I tested the multiple devices feature I found the Table **oc_twofactor_backup_codes** but it seemed to have no effect at all. After carefully renaming and much testing I deleted it because nothing seemed to miss it after a lot of testing.
Now I wanted to retest 1.3.0 (and then 1.3.1) with two plug-up U2F-Sticks because of this issue-thread https://github.com/nextcloud/twofactor_u2f/issues/45. After installing two sticks in a row and a relogin I got a server error.
![screenshot_4](https://cloud.githubusercontent.com/assets/3265671/25741064/67362652-3189-11e7-98cd-d531ff3163af.png)

The Log sais:

> Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `id`, `user_id`, `code`, `used` FROM `oc_twofactor_backup_codes` WHERE `user_id` = ?' with params ["Archiv"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_twofactor_backup_codes' doesn't exist

When I disable twofactor_u2f and enable twofactor_u2f this table is not inserted.
When I upgrade 1.3.0 to 1.3.1 it is not inserted as well.

I once removed this original table **oc_twofactor_backup_codes** and **oc_twofactor_u2f_registrations** and the datafolder to test the feature and its reliability. 
When I reinstalled the App it did create oc_twofactor_u2f_registrations but not oc_twofactor_backup_codes. (I guess, quite sure)

When I search **oc_twofactor_backup_codes** within the whole nextclouds mysql database, there are 0 results.

At this time I dont really now why oc_twofactor_backup_codes is needed nor why it is not created, but I guess that might have something to do with my Nextcloud updating?

**NOTE: This might be my own fault because of tempering with the app some weeks ago, but it might be some missing table definition as well. I cannot tell.**
![screenshot_3](https://cloud.githubusercontent.com/assets/3265671/25741075/703c81b0-3189-11e7-8e56-a75befe8447b.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/3265671/25741076/7061cb8c-3189-11e7-83af-4df2ec70217e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3265671/25741077/7068c022-3189-11e7-89a8-836aaef28d79.png)

**Comment by ChristophWurst** [comment]
> I once removed this original table oc_twofactor_backup_codes and oc_twofactor_u2f_registrations and the datafolder to test the feature and its reliability.

Don't do that. You deleted a table of the nextcloud server. Maybe an update will restore it.

The backup codes table definition lives in https://github.com/nextcloud/server/blob/619d09529c417df10ac57815024b89dee9285c35/apps/twofactor_backupcodes/appinfo/database.xml

**Comment by Nibbels** [comment]
Yes, 
When there is some App called "twofactor_backupcodes" I need the table too.
