### ISSUE TITLE
Unable to use u2f tokens on Firerfox

### ISSUE THREAD

**Issue by DanielVukelich** [nextcloud/twofactor_u2f#461]
### Steps to reproduce
0. Log into nextcloud on latest firefox version
1. Go to security tab
2. Try to add a u2f token
3. Plug the token in and press the button

### Expected behaviour
With Chromium, the token lights up.  When I press the button Nextcloud recognizes the device and prompts me to name it.

### Actual behaviour
The page prompts me to plug in my u2f device, and the spinner runs infinitely.  My token does not light up.

### Server configuration

**Operating system**: Arch Linux

**Web server:** NGINX

**Database:** mariadb

**PHP version:** 7.3.6

**Version:** 16.0.1

**Updated from an older version or fresh install:** Fresh

**List of activated apps:** twofactor_u2f

#### Client configuration
**Browser:** Firefox 67

**Operating system:** Arch Linux

##### Web server error log
```
None
```

##### Server log (data/nextcloud.log)
```
None
```

##### Browser log
```
starting u2f registration AddDeviceDialog.vue:109
Error: "Registration failed"
    u u2f-api.js:71
    register u2f-api.js:114
    register u2f-api.js:121
    S ncvuecomponents.js:148
    register u2f-api.js:111
    N ncvuecomponents.js:148
    N ncvuecomponents.js:148
    u ncvuecomponents.js:148
ncvuecomponents.js:148:37978
    N ncvuecomponents.js:148
    N ncvuecomponents.js:148
    u ncvuecomponents.js:148
```

**Comment by ChristophWurst** [comment]
Please fix your nginx config to also serve .js.map files. Then we'll get a readable error trace.

**Comment by DanielVukelich** [comment]
Ah, good point.  I've updated the ticket with a readable stack trace

**Comment by ExternalDatabase** [comment]
Hi Daniel,
have you tried to change your Firefox config?
about:config
security.webauth.u2f (from **false** to **true**)
With my FF 67 (x64, Fedora) and 60.7.1 ESR (x64, Windows) it works fine.

**Comment by hithroc** [comment]
I have the same issue, I have `security.webauth.u2f` set to `true` and U2F has worked on other sites so far.

**Comment by peckeltw** [comment]
> Hi Daniel,
> have you tried to change your Firefox config?
> about:config
> security.webauth.u2f (from **false** to **true**)
> With my FF 67 (x64, Fedora) and 60.7.1 ESR (x64, Windows) it works fine.

@DanielVukelich that is exactly what is needed: enabling U2F in Firefox will fix your issue.

**Comment by sodomak** [comment]
I have the same issue (and same configuration as Daniel), u2f enabled and it works well on other websites.

**Comment by DanielVukelich** [comment]
> Hi Daniel,
> have you tried to change your Firefox config?
> about:config
> security.webauth.u2f (from **false** to **true**)
> With my FF 67 (x64, Fedora) and 60.7.1 ESR (x64, Windows) it works fine.

I've been out of town for the next past two weeks, so I haven't been able to verify on the computer where I encountered this issue.  I'm pretty sure that I already have u2f enabled in my about:config, as I am able to log into other sites (like github) using this token on that machine, and I remember checking about:config when I first encountered this problem.  I can confirm that Firefox developer edition by default has u2f tokens enabled, since on this computer with recently installed Debian 9 has security.webauth.u2f set to true in about:config.

**Comment by DanielVukelich** [comment]
I have made no changes to about:config since returning from my trip, but the affected computer is now able to register the u2f token.  I did install a firefox update, so I can only assume that there was some bug in the browser that has since been fixed.

**Comment by RX14** [comment]
I am also experiencing this, `Error: "Registration failed"`. u2f works just fine on other websites, and the u2f test page on yubico's website works perfectly.

**Comment by RX14** [comment]
Entered the debugger and the `errorCode` of the result from `u2f.register` us `2` - corresponding to `BAD_REQUEST` from the u2f spec.

**Comment by RX14** [comment]
Here is the register request sent to the key

![](http://owo.sh/4mJuA8e.png)

seems fine. Not sure what's going on at all.

**Comment by ChristophWurst** [comment]
try https ;)

**Comment by RX14** [comment]
@ChristophWurst it is using https! But the appId is using the http scheme. I guess that breaks it.

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html. Nextcloud has to know the scheme. Set the url in the conig, then the app ID will be correct.

**Comment by returntrip** [comment]
I was having the same issue as @RX14 whilst using a Solokey. All I had to do is to add `'overwriteprotocol' => 'https',` to my `config/config.php`. I can now register my key successfully

**Comment by RX14** [comment]
Yes, `overwriteprotocol` fixes it. Bug was nextcloud not trusting my reverse proxy because of docker networking using a different IP. Would be nice if there was a nicer error message if the scheme was "http" though, since that's never going to work.

**Comment by ChristophWurst** [comment]
It is. FF is fine with it. But PRs are very welcome
