### ISSUE TITLE
Adaption to U2F API v1.1

### ISSUE THREAD

**Issue by go2sh** [nextcloud/twofactor_u2f#47]
This is a list of bugs currently in the U2F App which I found after a quick review.

- [ ] Database needs to store transports presented by a registration response
- [x] Challenge page needs to show a single challenge value and a list of registered keys
- [x] u2f app's challenge page needs to properly call u2f api with the correctly provided values
- [ ] Registration page needs to properly show registered keys and a single register request
- [ ] u2f app's register page needs to properly call u2f api with the correctly provided values

This the thing with multiple challenges is cause for breaking multiple devices. There might be some more bugs related to the items above.
cc @ChristophWurst  @LukasReschke

**Comment by zauguin** [comment]
@go2sh The first point isn't a bug, because storing the transports is optional according to the U2F spec.
The second and third should be fixed with #49.
Could you explain the last two points? I haven't really looked into it but I couldn't find fundamental problems with the registration on a first glance.

**Comment by ChristophWurst** [comment]
@go2sh @zauguin could you please re-check? I've swapped the u2f lib in #74, hopefully that fixed some of the items on your list.

**Comment by ChristophWurst** [comment]
I'm closing this because I got no response in more than three months. If this is still an issue, please let me know and I'll re-open.

Thank you for your report.
