### ISSUE TITLE
PIN option on Yubico U2F tokens not used with U2F 2FA

### ISSUE THREAD

**Issue by cyberbix** [nextcloud/twofactor_u2f#471]
### Question

Is the the PIN option that is available for Yubico tokens supposed to work ?

#### Summary

Yubico U2F tokens called "Security Key" - https://www.yubico.com/business/product/security-key-by-yubico/#security-key - provide an option to protect the token with an additional PIN, which is defined in the Yubikey Manager. When using a Yubico U2F key with this option, a U2F protected account, i.e. a Microsoft-Login, asks for the PIN before the user hast to touch the U2F token. 

This is not happening when authenticating with a Nextcloud instance configured for U2F. The option seems to be skipped.

Is this by design ?

**Comment by ChristophWurst** [comment]
I don't think https://github.com/grantila/u2f-api supports that, which iwe use for the cross browser u2f compatibility.

**Comment by ChristophWurst** [comment]
Eventually I would say that we only support the standard and no custom implementations. I'm wondering why this isn't handled by the browsers, after all the standard u2f interface could still be offered to the website.

Anyway, closing. Thanks for the feedback :)
