### ISSUE TITLE
Feature Request: Enforce U2F

### ISSUE THREAD

**Issue by NemoBarbarossa** [nextcloud/twofactor_u2f#50]
Hello team,

I really like the U2F plugin but I would love to have the possibility to enforce it for my users.

A similar think is currently in the works for TOTP over here: https://github.com/nextcloud/twofactor_totp/issues/41

Maybe there is a possibility for synergy here?

**Comment by Nibbels** [comment]
Well, this might some usecase but remember that if you enforce it for "all groups" you would not be able to log in with clients, caldav, webdav? 
Am I wrong?
Would APP-Passwords still work?
![screenshot_1](https://cloud.githubusercontent.com/assets/3265671/25910916/49af0234-35b2-11e7-9fb1-e60ab9493d00.png)

I guess that a solid plan is mandatory when it comes to enforcing second factor.

**Comment by ChristophWurst** [comment]
> Would APP-Passwords still work?

Yes, they are intended especially to be used with 2FA :)

**Comment by ChristophWurst** [comment]
> A similar think is currently in the works for TOTP over here: nextcloud/twofactor_totp#41

Same as over there: this should be a feature of the Nextcloud server component, so that *any* 2fa provider can be enforced.

**Comment by sporykhin** [comment]
Its also need to remember what user can disable this from their profile. This ability should be locked.

**Comment by ChristophWurst** [comment]
Let's continue this discussion in the server repo where it has to be implemented: https://github.com/nextcloud/server/issues/2348
