### ISSUE TITLE
wrong app ID in info.xml

### ISSUE THREAD

**Issue by Futosone** [nextcloud/twofactor_u2f#52]
Hello,
after activate the plugin with nextcloud 12.0 beta 2 I got this error:

```App for id twofactor_u2f has a wrong app ID in info.xml:```

**Comment by ChristophWurst** [comment]
Hi! Which version is that? How did you install the app?

**Comment by Futosone** [comment]
Hey,
I installed this over directly over the App-Store. But there is no version displayed.

**Comment by justusjonas74** [comment]
I've the same error.  Some more details: 
```

Error | core | App for id twofactor_u2f has a wrong app ID in info.xml: | 2017-08-04T07:12:19+0200
-- | -- | -- | --
Error | PHP | Trying  to get property of non-object at  /var/www/virtual/web41625.pfweb.eu/francisdoege.com/cloud/htdocs/lib/private/Installer.php#276 | 2017-08-04T07:12:19+0200
Error | PHP | Trying  to get property of non-object at  /var/www/virtual/web41625.pfweb.eu/francisdoege.com/cloud/htdocs/lib/private/Installer.php#271 | 2017-08-04T07:12:19+0200
Error | PHP | simplexml_load_file():  I/O warning : failed to load external entity  "/var/www/virtual/web41625.pfweb.eu/phptmp/oc_tmp_lxN7JF-folder//twofactor_u2f/appinfo/info.xml"  at  /var/www/virtual/web41625.pfweb.eu/francisdoege.com/cloud/htdocs/lib/private/Installer.php#269 | 2017-08-04T07:12:19+0200

```

**Comment by ChristophWurst** [comment]
> simplexml_load_file(): I/O warning : failed to load external entity "/var/www/virtual/web41625.pfweb.eu/phptmp/oc_tmp_lxN7JF-folder//twofactor_u2f/appinfo/info.xml" at /var/www/virtual/web41625.pfweb.eu/francisdoege.com/cloud/htdocs/lib/private/Installer.php#269 | 2017-08-04T07:12:19+0200

This could be the reason for the error.

**Comment by ChristophWurst** [comment]
Maybe @LukasReschke knows more about the app store code. Does the server unpack the archive to a temporary directory? Do we check whether that succeeds?

**Comment by DMeechan** [comment]
I'm getting the same error 'App for id twofactor_u2f has a wrong app ID in info.xml:' when trying to install it in the latest version of Nextcloud. Is currently there anything I can do on my end to fix it?

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/492#issuecomment-330829469

If this indeed turns out to be a general problem, we should move this to the server repo.

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/nextcloud/server/pull/6586
