### ISSUE TITLE
u2f nfc does not work on huawey smartphones

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/twofactor_u2f#538]
I have several keys u2f, including yubico 5 nfc, when I access nextcloud from samsung smartphone or google pixel and I click u2f authorization, the token page opens that asks me if the token is usb or nfc, I choose nfc I approach the key and authenticate me . this request for the type of key however does not occur with any huawey smartphone even on a pi20. clicking on u2f listens but does not ask what token I have unlike other brands of smartphones. cone solve on huawey for nfc token?

also tried on Huawei smartphones via usb-otg and nemneno va. there are problems on Huawei

google chrome use of course

**Comment by ChristophWurst** [comment]
what's the error?

**Comment by ChristophWurst** [comment]
also, please use the issue template. I have no clue which version of twofactor_u2f, Nextcloud, php or anything else you're using.

**Comment by tigernero79** [comment]
I meant to say that it is not possible to use u2f with huawei phones, the token choice does not come out and even if I connect it to a microusb-otg I cannot authenticate myself.

**Comment by tigernero79** [comment]
this screen does not appear on huawei

![Screenshot_20190916-142012](https://user-images.githubusercontent.com/35575744/64957433-3ef8ec80-d88d-11e9-90c9-271bfc13ddcc.png)

**Comment by ChristophWurst** [comment]
what app is this screen from? I've never seen that

**Comment by tigernero79** [comment]
@ChristophWurst enable u2f module in nextcloud.  although i hope in fido2, enter your credentials in nextcloud browser on Smartphone using google chrome mobile, it will ask you which key to use if u2f usb or u2f bluetooth or u2f nfc, I choose nfc and authenticate myself and access nextcloud on chrome, this window will  appears on both samsung and pixel smartphones but not on Huawei and I can't log in from chrome mobile

**Comment by ChristophWurst** [comment]
do you have the google authenticator app installed on both apps?

**Comment by tigernero79** [comment]
of course, I always use my yubico 5 nfc which also acts as a code generator s 6 digits toto, and so I access on smartphone huawey, yubico totp better than google authenticator, the codes always reside in the key.

**Comment by ChristophWurst** [comment]
> yubico totp better than google authenticator

so you actually **dont't** have google authenticator installed but an app from yubico?

**Comment by tigernero79** [comment]
if we talk about "totp" codes we use yubico authenticator app both for android, for "Windows" and for Mac. similar to Google authenticator.  I approach the NFC key if we talk about the Android version with an open yubico app and then I find the codes for the various services.  it works like Google authenticator but I use the nubc yubico series 5 key. but if we talk about totp, if we talk about u2f I approach the nfc key to my cell phone when requested and exit the choice of the token if it is USB, nfc or bluetooth.  I choose nfc close the key and I get double authentication.  this does not happen with Huawei smartphones.  does not let me choose the type of token.  that's all.

**Comment by tigernero79** [comment]
the problem was solved thanks to yubico.  it was enough to install google authenticator application for this mask to appear on all my mobile phones and allow me to use my u2f dongle by authenticating me via nfc.  what a funny thing.  I never thought that chrome for choosing the u2f interface depends on a second application.  solved anyway
