### ISSUE TITLE
String not translated when wait for inserting u2f device

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/twofactor_u2f#541]
### Steps to reproduce
1. go to login webpage nextcloud instance
2. insert username and password, press login
3. Select U2F device

### Expected behavior
Text underneath U2F icon should be localized

### Actual behavior
Text underneath U2F icon is English, the other text is localized.
Text displayed is: "Plug in your U2F device and press the device button to authorize."

### Server configuration

Nextcloud: 16.0.4
twofactor_u2f: 3.0.1

### Possible solution
I traced this back in my nextcloud instance:
/apps/twofactor_u2f/js/challenge.js
Line 61:
t("mail","Plug in your U2F device and press the device button to authorize.")
Replaced "mail" with "twofactor_u2f"  and now localized string is displayed.

There is also another occurrence of mail:
t("mail","An error occurred. Please try again.")
Maybe this one also has to be replaced

I couldn't find the file in the repository so I guess this has to to with how vue works. I could find 
https://github.com/nextcloud/twofactor_u2f/blob/master/src/components/Challenge.vue
The mail tag is still there for both strings

**Comment by ChristophWurst** [comment]
Whoops. My bad. I clearly used the wrong *app ID*. Mind submitting a PR?

**Comment by theorangepotato** [comment]
FYI: This issue can be closed thanks to PR #549

**Comment by mjanssens** [comment]
You are right, fix in #549
