### ISSUE TITLE
Make it workable without secound click

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/twofactor_u2f#57]
Hello,

I activate u2f and totp, so I have to select one of them after login. Would be nice if it will be possible to get booth options without one more click, like it is in gitlab, github or most of other clients. Would be great. Everything else works great, thanks for your work.

**Comment by brantje** [comment]
I second this, integrating the totp app with this would be nice to have

**Comment by ChristophWurst** [comment]
Yes, that would be a nice enhancement indeed.

From taking a quick look at the code, the form we submit on the 2fa page is generic and thus the server wouldn't actually prevent this enhancement. We just have to find a nice UI/UX to show all providers on a single page. Of course, that has to be generic enough to work with any possible 2FA provider.

Ref https://github.com/nextcloud/server/blob/c94dbddd12099418ed010284201ec90fb74111f9/core/Controller/TwoFactorChallengeController.php#L141-L181

May I ask you to open a ticket in the server repo?

**Comment by CordlessWool** [comment]
is opened
[https://github.com/nextcloud/server/issues/5640](https://github.com/nextcloud/server/issues/5640)

**Comment by ChristophWurst** [comment]
Thanks!
