### ISSUE TITLE
Addd Support for nextcloud 13

### ISSUE THREAD

**Issue by Hanzei** [nextcloud/twofactor_u2f#58]
This should also fix the failing tests,

**Comment by ChristophWurst** [comment]
Totally, though we should maybe do a final release for nc12 with all the translations. I won't release the app for nc13 as long as it's in development. Pushing an app too early turned out to be problematic in the past.

**Comment by Hanzei** [comment]
I understand your point. But why do you run the ci against the nc master branch which is 13?

**Comment by ChristophWurst** [comment]
Oh, good point. Actually it should run against stable12 and master. Hence the Travis config has a bug https://github.com/nextcloud/twofactor_u2f/blob/999ab1952a8bde923728e8bf5e4009c1c04e888f/.travis.yml#L90

**Comment by Hanzei** [comment]
But if your run it against master, wont it fail again?

**Comment by ChristophWurst** [comment]
Yes, it will. I have to clean this app.

I plan to do the following
* create a release based on the master branch – no functional changes, hence it should be fine to package and release it for nc12 like the last release
* adjust the info.xml to depend on nc12 to nc13 and also adjust the Travis test matrix accordingly

**Comment by Hanzei** [comment]
Do you want to do this by your self or is help wanted?

**Comment by ChristophWurst** [comment]
Feel free to help with this! :) PRs are always welcome!
