### ISSUE TITLE
Q; Error Persisting Registration

### ISSUE THREAD

**Issue by baltic-git** [nextcloud/twofactor_u2f#588]
### Question

I tried to register a yubikey. Key is recognized by the browser, but registration can't be completed. Browser shows wait symbol forever.

In the console, I see the following error:

[DEBUG] twofactor_u2f: registration was successful 
Found 0 logins for this site inject.js:324:29
[DEBUG] twofactor_u2f: persisting registration on server 
Object { app: "twofactor_u2f", uid: "admin" }
ConsoleLogger.js:44:18
[DEBUG] twofactor_u2f: confirmed password 
Object { app: "twofactor_u2f", uid: "admin" }
ConsoleLogger.js:44:18
[DEBUG] twofactor_u2f: saving registration data 
Object { app: "twofactor_u2f", uid: "admin", data: {…} }
ConsoleLogger.js:44:18
Found 0 logins for this site inject.js:324:29
**[ERROR] twofactor_u2f: Error persisting registration 
Object { app: "twofactor_u2f", uid: "admin", config: {…}, request: XMLHttpRequest, response: {…}, isAxiosError: true, toJSON: toJSON() }**
ConsoleLogger.js:56:18
    value ConsoleLogger.js:56
    value ConsoleLogger.js:82
    saveRegistrationData AddDeviceDialog.vue:184
[ERROR] twofactor_u2f: Error: Server-Fehler beim Versuch die U2F-Geräte-Registrierung abzuschließen 
Object { app: "twofactor_u2f", uid: "admin" }
ConsoleLogger.js:56:18
    value ConsoleLogger.js:56
    value ConsoleLogger.js:82

#### Summary
What do I need to do make Nextlcoud persist the key registration?

**Comment by ChristophWurst** [comment]
> What do I need to do make Nextlcoud persist the key registration?

Report this as a proper bug report: https://github.com/nextcloud/twofactor_u2f/issues/new?template=bug.md

**Comment by baltic-git** [comment]
FWIW: I was about to write a more detailed bug after I discovered that the issue only appeared when using U2F via a reverse proxy (nginx). However, after the update to version 5.0.1  everything works as expected.

Many thanks!

**Comment by ChristophWurst** [comment]
Hey, thanks a lot for the feedback.

Reverse proxies are like the \#1 issue with self-hosted u2f. Happy to hear it's working now!
