### ISSUE TITLE
U2f Support broken In firefox

### ISSUE THREAD

**Issue by chris4795** [nextcloud/twofactor_u2f#63]
I am using Firefox 50.1.0 In Debian Jessie, along with Nextcloud 12.0.2 anf U2F 1.3.3 plug in. I was previously able to use firefox's u2f plug in (verision 1.0.1) with Nextcloud, but now it only says an error occured. I am able to use the u2f function for github and fastmail, so I am suspecting there was something that was broken along the updates. 

Please let me know what logs to submit to help debugging.

Thank you!

**Comment by eddydevink** [comment]
Hi,

I had the same issue.
I used a backup code to login in. In my personal settings I deleted the u2f device and registered it again.
That fixed the problem for me.

**Comment by ChristophWurst** [comment]
Hi,

was there anything changed on your setups recently? E.g. did you update Nextcloud, this app, firefox or the u2f plugin?

**Comment by j-ed** [comment]
I'm not having any problems with Firefox 56.0 (Win7) and the U2F Support Add-on v1.0.1 together with Nextcloud 12.0.3 and the Two Factor U2F app v1.3.3. I only realized that I had to re-register my key if I've changed the Nextcloud configuration.

**Comment by ChristophWurst** [comment]
FYI native support for U2F in Firefox might land soon, it's already included and can be enabled experimentally: https://twitter.com/jamespugjones/status/912314952232267777 I'm using it on Firefox nightly and it works well with this app 😀

**Comment by ChristophWurst** [comment]
#74 should make this app's u2f handling a bit more stable.

**Comment by ChristophWurst** [comment]
I'm closing this ticket now since it has been inactive for quite a long time. Let me know (preferable in a new ticket) if you still face any problems with your u2f app.
