### ISSUE TITLE
U2F Auth fails when accessed from alternative domain

### ISSUE THREAD

**Issue by Cronixx** [nextcloud/twofactor_u2f#630]
### Steps to reproduce
1. Install nextcloud accessible from multiple (trusted) domains
2. Register U2F Device from one domain (e.g. cloud.mydomain.com)
3. Try to log into account secured by U2F Device from other (trusted) domain (e.g. cloud.my-domain.com)

### Expected behaviour
Tell us what should happen
It would be great to be able to log in from every trusted domain with my U2F device.

### Actual behaviour
Tell us what happens instead
The server only accepts my U2F Auth request when i connect via my regular domain.
I guess the U2F registration takes the current domain into account.
Would it be possible to add the ability to also add other accepted domains,
or would a new/additional registration be necessary?

Please tell me if you need me to provide additional information,
as i dont want to unnecessary provide details about my personal HSM, etc.

### Server configuration

**Operating system**: Debian Buster

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Version:** (see admin page) 5.0.2 (U2F Plugin) 

**Updated from an older version or fresh install:** Fresh

#### Client configuration
**Browser:** Firefox 68.2 esr

**Operating system:** Debian testing

**Comment by ChristophWurst** [comment]
That doesn't work as the u2f registration uses an `appId` parameter that is more or less the domain of the site. Hence you can't use the registration for another domain.
