### ISSUE TITLE
Bug - strange behavior with two networks

### ISSUE THREAD

**Issue by Larsene** [nextcloud/twofactor_u2f#64]
Hi, i encounter a strange behavior of this plugin on my NextCloud 12.0.3 install.

**1st test / distant access** 
Access trough web connexion 212.51.***.***
1- install this plugin from the nextcloud app
2- add an U2F Key for my account, naming it.
3- log out, then log in.. 
**Everything is working well**

**2nd test / local**
I went back to my workoffice, then i access to nextcloud from an internal IP (same computer, same U2F Key). Access through 172.20.90.***
1- **I got an error when i need to connect the key and push his button**. I can't connect my Nextcloud
2- Try to connect with ethernet cable instead of wifi, same result.
3- tried to reboot the computer, same result
4- tried to change the USB port used by ma U2F key, same result

![screenshot_2](https://user-images.githubusercontent.com/8544729/31068550-c9d9dd9a-a758-11e7-9a60-b077373a4c9d.jpg)

**3rd test / Tethering**
Then, i tried to connect my nextcloud through a Tethering access, as i didn't have my recovery password with me.
1- connect through my smartphone
2- as expected, the connection is okay. 
Then, i desactivate my 2nd authentification key, and i can work from my workoffice.

**4th test / reactivate U2F from my workoffice network**
Connected to my workoffice network, i log in to NextCloud, the re-register my U2F Key.
1- Log out, then log in : everything is fine, i can log in with my IDKey, no Pb.
2- i tried to access through tethering to Nextcloud. then, i can't use my U2F key to access. i got the same error message as in the second test.

So, i can use this U2F authentification only on a local network, OR a distant one, but not the two ! this is really annoying !

Please, could you take a look at this case ?

**Comment by ChristophWurst** [comment]
The registration is bound to the domain of the server. Nothing to do here, just always use the domain and it will work properly.
