### ISSUE TITLE
Cannot register yubikey

### ISSUE THREAD

**Issue by markmcb** [nextcloud/twofactor_u2f#647]
I'm unable to register a yubikey. It appears to be some sort of https issue. [I tried troubleshooting suggested in issue #540](https://github.com/nextcloud/twofactor_u2f/issues/540), but it didn't help.

In the console I see this:

```
Error: "U2F not supported"
    d u2f-api.js:88
    register u2f-api.js:113
```

The source of the first is definitely https related:

```
exports.isSupported = isSupported;
function _ensureSupport(backend) {
    if (!backend.u2f) {
        if (location.protocol === 'http:')
            throw new Error("U2F isn't supported over http, only https");
        throw new Error("U2F not supported");
    }
}
```

Overriding the line in `U2FManager.php` (per #540) doesn't seem to help either:

```
private function getU2f(): U2F {
        // $url = $this->request->getServerProtocol() . '://' . $this->request->getServerHost();
        $url = 'https://' . $this->request->getServerHost();
        return new U2F($url);
}
```

And for completeness, relevant lines from `config.php` and my nginx config:

```
'overwrite.cli.url' => 'https://[my domain]',
'overwriteprotocol' => 'https',
'trusted_proxies' =>
  array (
    0 => '127.0.0.1',
  ),
```

```
proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Proto $scheme;
proxy_pass          http://127.0.0.1:81;
```

### Server configuration

nextcloud snap on Ubuntu 19.10. Currently 16.0.7

No other issues with server. Works fine with both the web and iOS app clients.

Problem was reproducible in Firefox (71) and Chrome (79) on MacOS 10.15.2.

**Comment by theorangepotato** [comment]
I'm not certain that this is HTTPS related. If the protocol listed were `http:`, it would have given you a "U2F isn't supported over http, only https" error. Since it instead gave you "U2F not supported", that implies that the protocol is `https:`, no?

**Comment by markmcb** [comment]
The problem went away when the snap package was updated from v16 to v17. Still no idea what the problem was, but it's gone now so I'll close this.
