### ISSUE TITLE
U2F device registration error (code 4) message should be improved

### ISSUE THREAD

**Issue by j-ed** [nextcloud/twofactor_u2f#65]
## Expected behavior
If you erroneously try to register an already registered U2F key again, the displayed error message should tell you exactly that. 

## Current behavior
If you try to register an U2F key again the following error message is displayed which is not pointing to the root cause of the problem:

![20171006_u2f_registration_twice](https://user-images.githubusercontent.com/2572764/31274818-e0a2a9f0-aa94-11e7-9e50-c0bd117cbf63.png)

### Steps to reproduce
1. Open the personal settings and select 'U2F-Two factor authentication'.
2. Try to register an already registered U2F key again.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.0.3
Two Factor U2F app version: 1.3.3

#### Client Configuration
Browser: Mozilla Firefox 56.0
U2F Support Add-on version: 1.0.1
Operating system: Windows 7

**Comment by ChristophWurst** [comment]
> ChristophWurst added the Hacktoberfest label just now

@j-ed this should be realtively easy to fix and thus makes an easy PR for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 😉

**Comment by j-ed** [comment]
@ChristophWurst I need your advice on this. Based on the developer documentation the following return codes are possible:
```
1 - OTHER_ERROR               |
2 - BAD_REQUEST               |> U2F device registration failed
3 - CONFIGURATION_UNSUPPORTED |
4 - DEVICE_INELIGIBLE         -> U2F device has already been registered
5 - TIMEOUT                   -> U2F device registration timeout reached
```
To keep the number of translation strings low, I would tend to the assumption that case 4 and 5 are codes which might occur more likely and that the codes 1-3, which could be summarized. Would you agree on this?

**Comment by ChristophWurst** [comment]
> To keep the number of translation strings low, I would tend to the assumption that case 4 and 5 are codes which might occur more likely and that the codes 1-3, which could be summarized. Would you agree on this?

Those five translation strings don't hurt IMO, but I'm also okay with consolidating the first three - so it's up to you 😉

**Comment by My1** [comment]
while we are at it, unless already done also add those errors to login.
but 4 is different here. 4 on login means unknown device.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_u2f/pull/66. This should be fixed by that PR. But further improvements are of course welcome any time :)

**Comment by ChristophWurst** [comment]
I'm closing this ticket as solved. Let's discuss further ideas/enhancements in a new issue. Thanks everyone!

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_u2f/pull/66 :)
