### ISSUE TITLE
How to reset twofactor_u2f / delete ALL its settings?

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_u2f#662]
### Question

I'd like to reset twofactor_u2f to factory default / delete config/database stuff that leads to server error upon 2F-login.

#### Summary

In ONE of my NC instance, if I install twofactor_u2f I cannot login any longer: username and passphrase is asked but the screen to select which twofactor backend to use yields server error.
Deleting twofactor_u2f app directory restores normal operation.

See https://help.nextcloud.com/t/server-error-after-installing-twofactor-u2f/48690

**Comment by ChristophWurst** [comment]
As far as I can tell there is data in 

oc_u2f_registrations
oc_twofactor_providers

Randomly deleting some data won't solve problems, though. We should fix the bug instead.

**Comment by nursoda** [comment]
I'd prefer that, too. Please advise what to do: It's not THAT important to have U2F atm, as long as TOTP works fine, so I can leave it to retrieve data that helps to narrow down the issue. Concerning debugging: It's my production system with customer data that faces the issue…

**Comment by ChristophWurst** [comment]
> There are no tables with u2f in their name

is that still the case? Any u2f entries in `oc_migrations`?

**Comment by nursoda** [comment]
Yes. After deleting the twofactor_u2f record in oc_migrations, I could install and use the app fine. Sorry and thanks. Still learning.

Lessons learned:

At some time I must have deleted the twofactor_u2fapp folder AND the oc_u2f_registrations DB table. This manual action obviously does not remove the oc_migrations entry. But migrations are the representation of what the DB should look like. The DB itself is NOT checked: When installing, the app checks whether there are new migrations. As the entry was already there, it did not (re-)create the (missing) table.

To see an error in nextcloud.log, I should have switched logging from 4 (ctitical) to 3 (errors). Then use something like `jq` to beautify JSON, then read and find that the app complains about the missing table.
