### ISSUE TITLE
Add Backlink to 2FA selection

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_u2f#68]
it is kinda annoying when you select a 2FA provider and then realize you cant use it (no U2F stick at hand, wrong browser etc) that your only choices are backup code and cancel login.

in my opinion there should be a button that just brings you back to the list of challenges.

also why does the Backup code button come there? wouldnt it make more sense if that would be on the 2FA selection screen?

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/twofactor_totp/issues/202
