### ISSUE TITLE
New Edge Support

### ISSUE THREAD

**Issue by rizzodieratte** [nextcloud/twofactor_u2f#697]
Hello,

i really like the function on nextcloud with my yubikey.
Will the new microsoft edge be supported in the future?

**Comment by ChristophWurst** [comment]
Yes, as soon as the upstream u2f-api lib handles it, we will have it automatically: https://github.com/nextcloud/twofactor_u2f/blob/73fac6bf8bf6805be78f61830e3ea70249623ce2/src/components/PersonalSettings.vue#L59-L61
