### ISSUE TITLE
I think its time now to stop ignoring Microsoft Edge Chromium

### ISSUE THREAD

**Issue by Sociopaat** [nextcloud/twofactor_u2f#723]
Dear developers,

Still no support for Edge Chromium?
I can use U2F on every other site i use without any problems.
only Nextcloud is still not working.
seems like more and more ppl are using Edge Chromium now.
can you guys look in this?

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_u2f/issues/472
