### ISSUE TITLE
Trust browser after success

### ISSUE THREAD

**Issue by XSBen** [nextcloud/twofactor_u2f#775]
Can you add the possibility to trust the browser from which the connection has been established, so that for the following connections, the fido key is not requested?

This "trust" could be limited in time (1 week, 1 month ...).
It could also be linked to an IP.

Google provite this possibility : ("Don't ask me again on this computer"):

![image](https://user-images.githubusercontent.com/6490248/96224919-971e8880-0f90-11eb-852b-6b6b76e4b25e.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/2906
