### ISSUE TITLE
How to disable ?

### ISSUE THREAD

**Issue by oatmealm** [nextcloud/twofactor_u2f#806]
### Question

How would I disable this app on an account that that was enabled for u2f... it seems like the occ commands don't do much. U2f is still enforced after disabling providers and specifically clearing up a user.

**Comment by ChristophWurst** [comment]
2FA isn't enforced by this provider but a setting in the Nextcloud server. You have to disable it there.

For any follow-up questions please use the community forum: https://help.nextcloud.com/c/apps/twofactor-u2f/72
