### ISSUE TITLE
How to make U2F working behind haproxy

### ISSUE THREAD

**Issue by gergap** [nextcloud/twofactor_u2f#90]
Hi,

I've nextcloud running behind haproxy, which work in general, but not with U2F.
Maybe this is a "feature", that U2F detect the MITM, but in this case it is not an attack,
but a desired feature, that I can runn nextcloud behind haproxy.

I don't know the technical details on how U2F sends its challange/response over https (or uses it's separate connection?).
But actually there is a TLS connection from the browser to the haproxy with one haproxy-certificate.
So haproxy is the endpoints of this connection and creates a separate one to nextcloud via TLS.
This also means that haproxy sees the unecrpyted data, but both servers are under my control,
no problem here.

Any ideas why U2F does not work via haproxy? and how to fix this?

**Comment by ChristophWurst** [comment]
Hey,

please see https://docs.nextcloud.com/server/12/admin_manual/configuration_server/reverse_proxy_configuration.html. The U2F app should just work if Nextcloud is configured properly.

**Comment by ChristophWurst** [comment]
No feedback provided, so I'm assuming the linked documentation has helped resolving the problem.
