### ISSUE TITLE
Registration failed for YubiKey 4

### ISSUE THREAD

**Issue by gergelypolonkai** [nextcloud/twofactor_u2f#99]
I want to register my YubiKey on NextCloud 13.0.0. My instance is behind a reverse proxy (nginx). The proxy terminates SSL with a valid Let's Encrypt certificate.

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html and check whether your settings are correct. If the URL your browser sees does not match the one Nextcloud thinks its served from, U2F registration fails.

**Comment by gergelypolonkai** [comment]
According to the page you linked, it should be OK, but…

I had to set `overwriteprotocol` to `https`; I guess that’s because the proxy terminates SSL, not the NextCloud instance.  Maybe this worths a note in the README or in the documentation.

**Comment by ChristophWurst** [comment]
> I had to set overwriteprotocol to https; I guess that’s because the proxy terminates SSL, not the NextCloud instance. Maybe this worths a note in the README or in the documentation.

The Nextcloud documentation tells you exactly that and the problem is not specific to this app, hence it wouldn't make sense to add this here.

**Comment by gergelypolonkai** [comment]
NextCloud itself worked happily without this setting, hence my suggestion. Anyway, at least this issue is there for future reference :smile:
